networks:
  net-aspen:
volumes:
  solr:

services:
  backend:
    image: ${BACKEND_IMAGE_TAG:-aspendiscovery/aspen}
    env_file:
      - .env
    environment:
      - ASPEN_BACKEND=yes
    ports:
      - "80:80"
    networks:
      - net-aspen
    tty: true
    volumes:
      - ${ASPEN_DATA_DIR}/conf:/usr/local/aspen-discovery/sites/${SITE_NAME}
      - ${ASPEN_DATA_DIR}/data:/data/aspen-discovery/${SITE_NAME}
      - ${ASPEN_DATA_DIR}/logs:/var/log/aspen-discovery
    depends_on:
      db:
        condition: service_healthy

  cron:
    image: ${BACKEND_IMAGE_TAG:-aspendiscovery/aspen}
    env_file:
      - .env
    environment:
      - ASPEN_CRON=yes
    networks:
      - net-aspen
    tty: true
    volumes:
      - ${ASPEN_DATA_DIR}/conf:/usr/local/aspen-discovery/sites/${SITE_NAME}
      - ${ASPEN_DATA_DIR}/data:/data/aspen-discovery/${SITE_NAME}
      - ${ASPEN_DATA_DIR}/logs:/var/log/aspen-discovery
    depends_on:
      - backend
    entrypoint: cron -f -L 2

  db:
    image: ${MARIADB_IMAGE:-mariadb:10.5}
    restart: always
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD:-password}
      - MARIADB_USER=${DATABASE_USER:-user123}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD:-passwd}
      - MARIADB_DATABASE=${DATABASE_NAME:-aspen}
    volumes:
      - ${ASPEN_DATA_DIR}/database:/var/lib/mysql
    networks:
      - net-aspen
    healthcheck:
      interval: 60s
      retries: 10
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]

  solr:
    image: ${SOLR_IMAGE_TAG:-aspendiscovery/solr}
    env_file:
      - .env
    environment:
      - SOLR_PORT=${SOLR_PORT:-8983}
    ports:
      - "${SOLR_PORT}:${SOLR_PORT:-8983}"
    volumes:
      - solr:/var/solr
    networks:
      - net-aspen
    depends_on:
      - backend