version: '3.7'
networks:
  net-aspen:
services:

  backend:
    image: aspen-discovery/aspen:${COMPOSE_ImageVersion}
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - net-aspen
    tty: true
    volumes:
      - ~/${ASPEN_Instance}:/mnt
    depends_on:
      - db

  db:
    image: mariadb:10.3
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${COMPOSE_RootPwd}
    deploy:
      endpoint_mode: dnsrr
    volumes:
      - ~/${ASPEN_Instance}/mariadb_data:/var/lib/mysql
    networks:
      - net-aspen

  solr:
    image: aspen-discovery/solr:${COMPOSE_ImageVersion}
    env_file:
      - .env
    ports:
      - "${SITE_solrPort}:${SITE_solrPort}"
    deploy:
      endpoint_mode: dnsrr
    volumes:
      - ~/${ASPEN_Instance}/solr_data:/var/solr
    networks:
      - net-aspen
    depends_on:
      - backend
      
  tunnel:
    image: aspen-discovery/tunnel:${COMPOSE_ImageVersion}
    env_file:
      - .env
    deploy:
      endpoint_mode: dnsrr
    networks:
      - net-aspen
    depends_on:
      - backend