name: Publish Docker image to hub.docker.com
on:
  push

jobs:
  push_aspen_to_dockerhub:
    name: Push Aspen image to Docker Hub
    #if: ${{ always() && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            aspendiscoveryofficial/aspen:latest
            aspendiscoveryofficial/aspen:${{ steps.extract_branch.outputs.branch }}

  push_aspen_to_quay:
    name: Push Aspen image to Quay.io
    #if: ${{ always() && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            quay.io/aspen-discovery/aspen:latest
            quay.io/aspen-discovery/aspen:${{ steps.extract_branch.outputs.branch }}

  push_solr_to_dockerhub:
    name: Push Solr image to Docker Hub
    #if: ${{ always() && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: docker/solr/Dockerfile
          push: true
          tags: |
            aspendiscoveryofficial/solr:latest
            aspendiscoveryofficial/solr:${{ steps.extract_branch.outputs.branch }}

  push_solr_to_quay:
    name: Push Solr image to Quay.io
    #if: ${{ always() && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: docker/solr/Dockerfile
          push: true
          tags: |
            quay.io/aspen-discovery/solr:latest
            quay.io/aspen-discovery/solr:${{ steps.extract_branch.outputs.branch }}

  push_tunnel_to_dockerhub:
    name: Push Tunnel image to Docker Hub
    #if: ${{ always() && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: docker/tunnel/Dockerfile
          push: true
          tags: |
            aspendiscoveryofficial/tunnel:latest
            aspendiscoveryofficial/tunnel:${{ steps.extract_branch.outputs.branch }}

  push_tunnel_to_quay:
    name: Push Tunnel image to Quay.io
    #if: ${{ always() && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: docker/tunnel/Dockerfile
          push: true
          tags: |
            quay.io/aspen-discovery/tunnel:latest
            quay.io/aspen-discovery/tunnel:${{ steps.extract_branch.outputs.branch }}
